import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Header from "@/components/layout/Header";
import FireBbAnimation from "@/components/util/FireBbAnimation";

const Home: NextPage = () => {
  return (
    <div className="bg-white">
      <FireBbAnimation />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="w-full h-[calc(100vh-80px)] flex items-center justify-center">
        <div className="-mt-[17vh] relative">
          <div className="flex-grow z-30 relative">
            <h1 className="text-7xl font-extrabold text-center">Expense Tracker</h1>
            <h3 className="text-xl ml-1 mt-3 font-extrabold text-center">
              {"'The secret to getting ahead is getting started.'"}
            </h3>
          </div>

          <div className="mt-6">
            <Link href="/login">
              <button className="mx-auto flex items-center bg-black hover:bg-black/80 text-white backdrop-blur-sm px-5 py-3 rounded-xl font-semibold">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="mr-3 w-[30px] text-white"
                  viewBox="0 0 512 512"
                  fill="currentColor"
                >
                  <title>Person Circle</title>
                  <path d="M258.9 48C141.92 46.42 46.42 141.92 48 258.9c1.56 112.19 92.91 203.54 205.1 205.1 117 1.6 212.48-93.9 210.88-210.88C462.44 140.91 371.09 49.56 258.9 48zm126.42 327.25a4 4 0 01-6.14-.32 124.27 124.27 0 00-32.35-29.59C321.37 329 289.11 320 256 320s-65.37 9-90.83 25.34a124.24 124.24 0 00-32.35 29.58 4 4 0 01-6.14.32A175.32 175.32 0 0180 259c-1.63-97.31 78.22-178.76 175.57-179S432 158.81 432 256a175.32 175.32 0 01-46.68 119.25z" />
                  <path d="M256 144c-19.72 0-37.55 7.39-50.22 20.82s-19 32-17.57 51.93C191.11 256 221.52 288 256 288s64.83-32 67.79-71.24c1.48-19.74-4.8-38.14-17.68-51.82C293.39 151.44 275.59 144 256 144z" />
                </svg>
                <div className="text-2xl">
                  Get Started
                </div>
              </button>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

// export async function getStaticProps() {
//   const { data } = await supa.from("test").select("*").order("created_at");

//   return {
//     props: {
//       data,
//     },
//   };
// }

export default Home;
